name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-22.04 # Explicitly specify the Ubuntu version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build the site
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: npm run build

    - name: Debug build output
      run: ls -l ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./build
